version: '3'

services:

  airflow:
    build:
      context: ..
      dockerfile: docker/airflow/Dockerfile
    # image: apache/airflow:2.9.1
    container_name: airflow
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../output:/opt/airflow/output
      - ../pipelines:/opt/airflow/pipelines
      - ../lineage:/opt/airflow/lineage

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    command: standalone

  spark:
    image: apache/spark:3.5.1
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
